version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Levs192
      MONGO_INITDB_ROOT_PASSWORD: pas12345

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Levs192
      ME_CONFIG_MONGODB_ADMINPASSWORD: pas12345
      ME_CONFIG_MONGODB_URL: mongodb+srv://Levs192:pas12345@cluster0.qyfuqkk.mongodb.net/DB_USERS?retryWrites=true&w=majority