version: '3'
services:
  app:
    image: simplejack-app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - .:/app
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Levs192
      MONGO_INITDB_ROOT_PASSWORD: pas12345